name: Setup Swift
description: Setup a Swift environment on Ubuntu or macOS
author: Frederik Wallner
inputs:
  swift-version:
    description: Swift version to configure
    required: true
    default: "latest"
  allow-patch:
    description: Allow a requested x.y version to resolve to x.y.z without failing
    default: "false"
  skip-verify-signature:
    description: Skip GPG signature verification where applicable
    default: "false"
outputs:
  version:
    description: The full Swift version that was configured
runs:
  using: node24
  main: dist/index.js
branding:
  icon: "command"
  color: "orange"
